### ISSUE TITLE
Issue with getting data using AJAX

### ISSUE THREAD

**Issue by runestonestudios** [aniruddhanath/jquery-hotspot#2]
Hi,

When i'm trying to fetch the data using AJAX, i need to pass data to the webservice that i'm calling but when the webservice is called it says no parameter is found and throws an error. The code i'm using is as follows:

var values = { imageId: "HotspotPlugin-b" };
$("#divHotspotTest").hotspot({
            mode: "admin",
            // uncomment
            ajax: true,
            ajaxOptions: {
                url: 'QuestionPack.aspx/GetHotspotData',
                data: JSON.stringify(values),
                type: 'GET',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                processData: false,
                success: function (response) {
                    console.log("Success Hotspot b: ", response);
                    alert("Success Hotspot ", response.d);
                },
                error: function (response) {
                    console.log("Error Hotspot b: ", response);
                    alert("Error hotspot b ", response.status);
                }
            },
            LS_Variable: "HotspotPlugin-b",
            done_btnId: 'done-b',
            remove_btnId: 'remove-b',
            server_btnId: 'server-b',
            done_btnClass: 'btn btn-success controls',
            remove_btnClass: 'btn btn-danger controls',
            sync_btnClass: 'btn btn-info controls',
            afterSave: function (message) {
                alert(message);
            },
            afterRemove: function (message) {
                alert(message);
                window.location.reload();
            },
            afterSyncToServer: function (message) {
                alert(message);
            }
        });

Any help would be appreciated. Thanks in advance!

**Comment by aniruddhanath** [comment]
Apparently there a small bug in the code related to ajax storing. I have fixed it now.

**Comment by runestonestudios** [comment]
Still the same issue. using the same code as above. if possible could you add an example?

**Comment by aniruddhanath** [comment]
You don't have to define the data in your ajax options.
Also the callback should not be declared while initiating the plugin. It is included directly in the plugin.

Change your code to this:

```
$("#divHotspotTest").hotspot({
    mode: "admin",
    ajax: true,
    ajaxOptions: {
        url: 'QuestionPack.aspx/GetHotspotData',
        type: 'GET'
    },
    LS_Variable: "HotspotPlugin-b",
    done_btnId: 'done-b',
    remove_btnId: 'remove-b',
    server_btnId: 'server-b',
    done_btnClass: 'btn btn-success controls',
    remove_btnClass: 'btn btn-danger controls',
    sync_btnClass: 'btn btn-info controls',
    afterSave: function (message) {
        alert(message);
    },
    afterRemove: function (message) {
        alert(message);
        window.location.reload();
    },
    afterSyncToServer: function (message) {
        alert(message);
    }
});
```
